<?php
/**
 * This script is meant to make changing all of the wmde irc hooks very easy
 * Currently github doesnt make it easy to change some settings or change mass hooks!
 * See $hookTargets and $hookParams below!
 * @author Adam Shorland
 */

/**
 * Repositories to add / alter the irc hook for
 */
$hookTargets = array(
	'wmde' => array(
		'DataValuesJavascript',
		'ValueView',
		'WikibaseDataModel',
		'WikibaseDataModelSerialization',
		'DataTypes',
		'Ask',
		'WikibaseInternalSerialization',
		'Serialization',
		'AskSerialization',
		'WikidataBuilder',
		'wikidata-analysis',
		'WikibaseDatabase',
	),
	'DataValues' => array(
		'Geo',
		'Number',
		'Common',
		'Interfaces',
		'DataValues',
		'Serialization',
		'Validators',
		'Time',
		'Iri',
	),
);

/**
 * Params for the irc hook
 */
$hookParams = array(
	'name' => 'irc',
	'active' => true,
	'config' => array(
		'server' => 'chat.freenode.org',
		'port' => '7000',
		'room' => '#wikidata',
		'nick' => 'github-wmde',
		'ssl' => '1',
	),
	'events' => array(
		'push', 'pull_request', 'commit_comment', 'pull_request_review_comment'
	),
);

/**
 * Script starts below...
 */

// This file is generated by Composer
require_once 'vendor/autoload.php';

echo "Please generate a personal access token at https://github.com/settings/applications\n";
echo "Github Token:";
$token = stream_get_line(STDIN, 1024, "\n");

$client = new \Github\Client();
$client->authenticate( $token, null, \Github\Client::AUTH_HTTP_TOKEN );

foreach( $hookTargets as $user => $repos ) {
	foreach( $repos as $repo ) {
		addHook( $client, $user, $repo, $hookParams );
	}
}

/**
 * @param \Github\Client $client
 * @param string $user
 * @param string $repo
 * @param array $hookParams
 */
function addHook( $client, $user, $repo, $hookParams ) {
	/** @var Github\Api\Repo $githubRepos */
	$githubRepos = $client->api( 'repo' );

	$hooks = $githubRepos->hooks()->all( $user, $repo );
	$id = findCurrentIrcHookId( $hooks );
	if( !$id ){
		$githubRepos->hooks()->create( $user, $repo, $hookParams );
	} else {
		$githubRepos->hooks()->update( $user, $repo, $id, $hookParams );
	}
}

/**
 * @param array $hooks
 *
 * @return bool|int false or the id of the hook
 */
function findCurrentIrcHookId( array $hooks ) {
	foreach( $hooks as $hook ) {
		if( $hook['name'] === 'irc' ) {
			return $hook['id'];
		}
	}
	return false;
}